### ISSUE TITLE
Chybný hešovací algoritmus v kapitole o Gitu

### ISSUE THREAD

**Issue by peshek-of-rattay** [singularis-mzf/linux-spellbook#14]
V kapitole o Gitu se píše: "_Úplná MD5 heš je vhodná pouze ve skriptech, na ruční použití je nepraktická._"
Git ale používá hešovací algoritmus SHA-1, nikoliv MD5.

**Comment by singularis-mzf** [comment]
Děkuji za upozornění. Oprava vyjde ve verzi vanilková příchuť 2.4.
