### ISSUE TITLE
Bylo by dobré to pojmenovat „GNU/Linux Kniha kouzel 2.0“

### ISSUE THREAD

**Issue by bedna-KU** [singularis-mzf/linux-spellbook#3]
Bylo by dobré to pojmenovat „GNU/Linux Kniha kouzel 2.0“, protože o Linuxu (jádře) tam není prakticky nic a ta kniha se věnuje operačnímu systému GNU/Linux.

Toto som len preposlal. [Originál](https://www.abclinuxu.cz/zpravicky/linux-kniha-kouzel-2.0#1)

**Comment by singularis-mzf** [comment]
Jak jsem už napsal/a tam, úplně správný název by byl „Ubuntu: Kniha kouzel“, ale důvody pro změnu mi nepřipadají dost naléhavé, abych kvůli tomu projekt přejmenoval/a.

Jinak, jádro není úplně mimo oblast zájmu Linuxu: Knihy kouzel; už nyní je tam alespoň možnost [vypsat seznam nainstalovaných jader](https://singularis-mzf.github.io/v2/sprava-balicku.htm#cast3x6) a pojednání o „jaderných démonech“ v kapitole [Systém](https://singularis-mzf.github.io/v2/system.htm) a do budoucna plánuji i kapitolu o GRUBu a zavádění, kde by měly být zdokumentovány různé volby jádra a možná i práce s jadernými moduly jako takovými.

**Comment by bedna-KU** [comment]
To je presne to na čo Franta narážal, píšeš o GNU nástrojoch a názov je Linux.
![gnu_grub](https://user-images.githubusercontent.com/4377084/94984675-cd024c80-054e-11eb-9062-9e2d1b14e44b.jpg)

**Comment by singularis-mzf** [comment]
Jenže o GNU nástrojích nepíšu proto, že jsou GNU, ale proto, *že je používám na Linuxu* (tzn. na linuxovém jádře) a proto, že jsou svobodný nebo open-source software; píšu i o spoustě programů a nástrojů, které nejsou GNU (např. vim, xxd, git, youtube-dl, btrfs-progs, dpkg, apt, snapd – opravte mě, pokud se mýlím). Tak, jako je Linux (jádro) jen malou (byť důležitou) částí celého operačního systému, i GNU nástroje jsou už jen jeho malou částí a ne tak důležitou, aby vůbec měla být zastoupena v názvu. Dovedu si představit i název „Systemd: Kniha kouzel“, a přesto by ten projekt mohl mít stejný obsah jako má v současnosti a dávalo by to podobný smysl (byť ne úplně stejný).

Podle mého záměru tento projekt není o GNU nástrojích, a pokud najdu pro nějaký úkol konkurenční ne-GNU nástroj, který bude alespoň stejně svobodný, alespoň stejně dostupný (na Ubuntu) a v něčem lepší, bez váhání s ním GNU nástroj nahradím.

**Comment by bedna-KU** [comment]
[Co je GNU/Linux?](https://www.debian.org/releases/stable/s390x/ch01s02.cs.html)

**Comment by singularis-mzf** [comment]
> [Co je GNU/Linux?](https://www.debian.org/releases/stable/s390x/ch01s02.cs.html)

**Krátká odpověď:** [Synekdocha](https://cs.wikipedia.org/wiki/Synekdocha)

**Dlouhá odpověď:**
Ten článek jsem si přečetl/a, ale připadají mi z něj k tématu relevantní jen dvě věty: „*Protože jádro samotné netvoří funkční operační systém, preferujeme pro označení takovýchto systémů termín „GNU/Linux“. (Lidé obvykle říkají „Linux“, ale mají tím na mysli GNU/Linux.)*“

Na to odpovídám, že nejsem vývojář Debianu, takže se necítím vázán/a rozhodnutím komunity Debianu a mám plné právo říkat či psát „Linux“ a myslet tím to, co oni nazývají „GNU/Linux“.

Používat slovo „Linux“ k označení čehokoliv, v čem je Linux (jádro) obsažen, tedy třeba i svého počítače, kde je Linux nainstalovaný, nebo instalačního DVD, je v českém jazyce normální jazykový obrat, nazývá se [synekdocha](https://cs.wikipedia.org/wiki/Synekdocha), a trochu mě mrzí, že to komunita Debianu nechápe a trvá na používání odborné terminologie i tam, kde to zdaleka není nutné.

**Comment by singularis-mzf** [comment]
Když tak tu issue nechám otevřenou alespoň týden, aby se mohli vyjádřit všichni, kdo budou chtít...

**Comment by bedna-KU** [comment]
OK, dík.
